[google_service_account]
type = "service_account"
project_id = "liev-wp4-nl"
private_key_id = "3d5a496e1b5ad4d0d790bfccccf24b320f1621b0"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCVj+6I5dK41Mj9\nHGF68d1pchuKXAfyExmWtPUwahOrSe66rvj+ytyEoydajRiNVzCiZ5YbT1+e3iMx\nt0VK0KXWJb4QWBt0cjFK4Gn5xd0292XkZJYcixejZ55cO9f5CK39NoyPvFdAsnwd\nq8QFtR07RWKVT4dpkFDVObpNmBlmIP6XT9SiaBxZaPPaHsqxGueuIJfb0SPjCfnB\nj6H9K8T+Oft24jd8uJwm2+zO3V7KC0LX3KaN+uJc2YB1IsL0wfDn2dPOuoFK33Rj\nvy9oCHYKCwkFin6YSRlzV5f+cBxVTfvv/mhSPXEquvVYkm9M+OAiUj8kfRoAy9gw\nV2T4c7/TAgMBAAECggEANvoeAleM0qFxMk1s7c8bhwfJZN44k3z+4n2pRX8wtL2s\nEhaAc9RpJB5/OFN2S3pZ59DxBh/ys8jPIhbO01YIJ8Re7c4dZXwWb4I3ondfvjVJ\n0J9C6MIeUdQki5354VKV9mbHW4ytfBw/8H4zw69US/XQ67a8vYqtk/uw5pX6/CWj\n4itIyT+Xa+3WWzt0eH+jPmyIQEEeChGEY7KR2ckItuE9Bb6jD1V886tkz/lELTAI\nPgTwcA9zYRZo5ClnjyWO6PNsF22IBZhlCTpUBgxZi004DZdYRrsGIuggpPUNBgi9\ngY5ufRB1qT4hhESI3+HzdLyS7/benSl89kUdYVfOlQKBgQDGNtzeXHwx5f/DtFhA\nE6JSb2/ia50mRiGMMxAXephnq1OHwJDhFpn8JlyBy4aHO6sgw48yPj1xDAJpZUCW\nVGaf0EjUNOjC3NoelIjnkOSDRLbNnD9FoDENd6O2y9iCtxpVSNgBKoj9RJLCgYdN\n3RYdxAWQ+B+mY+VuKGRl6ZIWXQKBgQDBKhDQs9QSwIEMDFvWcRJr8EuBJwOJHJCK\niHfSAISZUTNQsUH9TO8gW+H9kjaFBnLSG7qGs2h1A3A1fDfvFPjCgnYLK2RI/818\nWHCk/+/w1ym4z/2HECus8I7QRhx1k7SHqEWTWeUVPDVFmNcUfUsHdIZVRq8Rf0hb\nssa2tRhr7wKBgQCF4YSpxLo2Ue3BWEzLaveWyqI9wwYwVepO8iaKVUofq78N0GmL\nP2Lex2JwYPIK4aiixrQv8Y46jywJ2FQZtgRjKaIng108UUQap6UZE+rlJ0J5+nFa\nK+s193ti+qjREa/9rugHUZ2Zw/mE20xysURA8qf31UA7ePn8v9egZnVAGQKBgAb9\nwsYK/C4Bkaoh+GD2jrghZloyU0pvIjwhXFTZd/MkoTrWb5D/a9g7+x32YMrHxPgd\n0M53R9yUV0dYS533oFlJ54PX+jU6LPHHMayHJuQMpZHu1TpCN5J20nRvVTBcPDh8\nuqfupP/zwenW8lHnhwOqEAKeIE/9z1yiR9btDwk5AoGBALcyC6dQbMqoYGgynBLs\n+VpWcCuum69IWGbuod3FA+8nVhKiHMdG1TxoyTzq+kF19+mrb1csBCE/r3dc+jGK\nBl6Vid+mvT0ni8NLdGF4tymTXeD5wRPTcGblJShD5GXX6NkCenKtGRMFeHUzHcxZ\n5SSdKPKf4+L39rwlaiO2OjQS\n-----END PRIVATE KEY-----\n"
client_email = "liev-wp4-nl@liev-wp4-nl.iam.gserviceaccount.com"
client_id = "115355983658766602695"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/liev-wp4-nl%40liev-wp4-nl.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[connections.postgresql]
dialect = "postgresql"
host = "nozomi.proxy.rlwy.net"
port = "41513"
database = "railway"
username = "postgres"
password = "MqfnsRlNKKDEYqHqFAolwLUmDZmUHQBZ"
